apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.admission.certmanager.k8s.io
spec:
  group: admission.certmanager.k8s.io
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: "{{ template "cert-manager.webhook.serviceName" . }}"
    namespace: {{ .Release.Namespace | quote }}
  version: v1beta1
