apiVersion: v1
kind: Service
metadata:
  name: "{{ template "cert-manager.webhook.serviceName" . }}"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "cert-manager.name" . }}
    chart: {{ template "cert-manager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    targetPort: 443
  selector:
    app: {{ template "cert-manager.name" . }}-webhook
    release: {{ .Release.Name }}
